openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
  description: API for user creation and authentication.

paths:
  /users:
    post:
      tags: 
        - Users
      summary: Create a new user
      operationId: createUser
      requestBody:
        description: User creation data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                firstName:
                  type: string
                lastName:
                  type: string
                credentials:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: string
                enabled:
                  type: boolean
              required:
                - username
                - email
                - firstName
                - lastName
                - credentials
                - enabled
      responses:
        '201':
          description: User created successfully
          content: {}

  /users/auth:
    post:
      tags: 
        - Users
      summary: Authenticate user and get access token
      operationId: authenticateUser
      requestBody:
        description: User login data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: integer
                  refresh_expires_in:
                    type: integer
                  refresh_token:
                    type: string
                  token_type:
                    type: string
                  not-before-policy:
                    type: integer
                  session_state:
                    type: string
                  scope:
                    type: string
                required:
                  - access_token
                  - expires_in
                  - refresh_expires_in
                  - refresh_token
                  - token_type
                  - not-before-policy
                  - session_state
                  - scope
