spring:
  application:
    name: youtcerts-users-tracking
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081

youtcerts:
  auth-server:
    url: http://localhost:8080
    authentication-path: /realms/users/protocol/openid-connect/token
    client-id: client_id
    client-secret: client_secret



