spring:
  application:
    name: youtcerts-users-tracking
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


youtcerts:
  auth-server:
    url: http://localhost:8080
    client-id: client_id
    client-secret: client_secret



